**************************************************
NWBInspector Report Summary

Timestamp: 2022-08-02 15:44:41.530613+07:00
Platform: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.35
NWBInspector version: 0.4.5

Found 5 issues over 1 files:
       2 - ERROR
       3 - BEST_PRACTICE_VIOLATION
**************************************************


0  ERROR
========

0.0  /tmp/nwb_versions/sub-112_ses-Ca-VS-VR-4.nwb: check_table_values_for_dict - 'None' object with name 'None'
       Message: Traceback (most recent call last):
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 496, in run_checks
    output = check_function(nwbfile_object)
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/nwbinspector/register_checks.py", line 131, in auto_parse_some_output
    for result in output:
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/nwbinspector/checks/tables.py", line 175, in check_table_values_for_dict
    if not hasattr(column, "data") or isinstance(column, VectorIndex) or not isinstance(column.data[0], str):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 351, in h5py._selector.Reader.read
  File "h5py/_selector.pyx", line 151, in h5py._selector.Selector.apply_args
IndexError: Index (0) out of range for empty dimension


0.1  /tmp/nwb_versions/sub-112_ses-Ca-VS-VR-4.nwb: check_table_values_for_dict - 'None' object with name 'None'
       Message: Traceback (most recent call last):
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 496, in run_checks
    output = check_function(nwbfile_object)
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/nwbinspector/register_checks.py", line 131, in auto_parse_some_output
    for result in output:
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/nwbinspector/checks/tables.py", line 175, in check_table_values_for_dict
    if not hasattr(column, "data") or isinstance(column, VectorIndex) or not isinstance(column.data[0], str):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 783, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/anh/.conda/envs/nwb_explorer/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 151, in h5py._selector.Selector.apply_args
IndexError: Index (0) out of range for empty dimension


1  BEST_PRACTICE_VIOLATION
==========================

1.2  /tmp/nwb_versions/sub-112_ses-Ca-VS-VR-4.nwb: check_roi_response_series_link_to_plane_segmentation - 'RoiResponseSeries' object at location '/processing/ophys/fluorescence'
       Message: rois field does not point to a PlaneSegmentation table.

1.3  /tmp/nwb_versions/sub-112_ses-Ca-VS-VR-4.nwb: check_empty_table - 'PhotodetectorsTable' object with name 'photodetectors'
       Message: This table has no data added to it.

1.4  /tmp/nwb_versions/sub-112_ses-Ca-VS-VR-4.nwb: check_empty_table - 'ExcitationSourcesTable' object with name 'excitation_sources'
       Message: This table has no data added to it.

